name: Copy Repo to D Drive

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy to D:\test
        run: |
          if (Test-Path "D:\test") {
            Remove-Item "D:\test\*" -Recurse -Force
          } else {
            New-Item -ItemType Directory -Path "D:\test"
          }
          Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination "D:\test" -Recurse
        shell: pwsh
